### ISSUE TITLE
PyYAML Incompatible changes in version 5.1

### ISSUE THREAD

**Issue by acoul** [coxley/aspath_graph#6]
`  File "/usr/lib/python2.7/site-packages/aspath_graph-1.3-py2.7.egg/aspath_graph/cli.py", line 132, in parse_yaml
    content = yaml.load(f)
  File "/usr/lib/python2.7/site-packages/yaml/__init__.py", line 109, in load`

https://github.com/yaml/pyyaml/issues/265
[aspath_safe_load_patch.txt](https://github.com/coxley/aspath_graph/files/3100125/aspath_safe_load_patch.txt)

**Comment by coxley** [comment]
@acoul Thanks for submitting the issue! I'll apply that push and submit a PR

In the future if you know the code required to fix a bug on our side, you can [submit a pull request](https://help.github.com/en/articles/creating-a-pull-request) to avoid waiting as long for me to respond :)
